### ISSUE TITLE
Saving chat data to *.txt file

### ISSUE THREAD

**Issue by Tannerid** [zerodytrash/TikTok-Livestream-Chat-Connector#10]
Hey, thats really good idea to make that script. It will helps to make the shows more interactive. 
Can you add an ability to save all that data to txt-file in real-time?
(honestly I need the function to forward that data to com-port, but txt-file is fine too)

**Comment by zerodytrash** [comment]
Hi, saving comments to a text file is possible with a few lines of code. Here is an example:

````javascript
let { WebcastPushConnection } = require('tiktok-livestream-chat-connector');
let { createWriteStream } = require('fs');

let connection = new WebcastPushConnection('@username')

connection.connect().then(() => { }).catch(err => console.error(err));

let chatLogFile = createWriteStream('chat.txt', { flags: 'a' });

connection.on('chat', (data) => {
    chatLogFile.write(`${data.uniqueId}: ${data.comment}\n`);
})
````

**Comment by Tannerid** [comment]
Awesome. Thanks!
