### ISSUE TITLE
Error to connect

### ISSUE THREAD

**Issue by GrosChien2Chasse** [zerodytrash/TikTok-Livestream-Chat-Connector#12]
We have an error on the launch, `Failed to connect Error: Failed to retrieve room_id from page source. mainPageHtml.match is not a function`

The error is on the demo too

![image](https://user-images.githubusercontent.com/100127165/154932195-5ab79c83-4171-4482-9879-687ba7eb6c2b.png)

**Comment by OlegShklyarov** [comment]
Same error. Is seems TT has changed something.

**Comment by OlegShklyarov** [comment]
It works again.

**Comment by GrosChien2Chasse** [comment]
nice
