### ISSUE TITLE
TT ignores some words sent in chat

### ISSUE THREAD

**Issue by OlegShklyarov** [zerodytrash/TikTok-Livestream-Chat-Connector#15]
Hello, is this TT issue? When I type these words in chat (any of them) they do not appear in  msg.comment.
Do you have any ideas why? They are not offensive or something. Just usual things.

рогатка помощь абзац стадо

**Comment by zerodytrash** [comment]
The sentence is filtered by TikTok. Even on TikTok itself it does not appear in the chat. Only the sender can see the message in the chat.

**Comment by OlegShklyarov** [comment]
Thanks for explanation.
