### ISSUE TITLE
Axios proxy bug

### ISSUE THREAD

**Issue by Davincible** [zerodytrash/TikTok-Livestream-Chat-Connector#18]
Turns out axios is a dump when it comes to proxies, and the default env proxy configurations cause axios to crash;
https://github.com/axios/axios/issues/3384

Not sure if there's a fix available, but would be nice to be able to use proxies here

**Comment by zerodytrash** [comment]
An option to pass a custom `httpsAgent` would be good. This also allows to use different proxies for each connection.
I'll put this on the ToDo list.

**Comment by zerodytrash** [comment]
It gets a bit more complicated. Axios does not support a custom httpsAgent because it already uses cookie jar's agent. Will try to find a solution.

**Comment by zerodytrash** [comment]
I removed axios-cookiejar-support and built my own cookie manager.
Now custom agents should work. Here is an example:

https://github.com/zerodytrash/TikTok-Livestream-Chat-Connector#connect-via-proxy
