### ISSUE TITLE
Can't find the user.

### ISSUE THREAD

**Issue by Bananonz** [zerodytrash/TikTok-Livestream-Chat-Connector#2]
Hi! 
When i try to read a chat live, the package don't find the user, i followed the guide but it wont work
I have cloned the public website too but it's isnt working, it's working only your website.

Error: Failed to extract room_id from page source. User might be offline.

**Comment by zerodytrash** [comment]
hi,
have you tried it with different users? I have tested it with several users from the TikTok Live trending page without any problems. Make sure you use the @username and not the display name. Maybe you can give me the name if there are still problems.

**Comment by Bananonz** [comment]
Hi! I have tryed with different accounts, the first was @officialboysgirls, then I used random tiktoker from my fyp, the only thing that I don't understand is that the only website that is working is your and not my clone.

**Comment by zerodytrash** [comment]
You are using the code from https://github.com/zerodytrash/TikTok-Chat-Reader ?
Maybe you get a captcha request from TikTok. Try it with a different IP.
