### ISSUE TITLE
Cannot read 'security' of undefined

### ISSUE THREAD

**Issue by mrsydster** [zerodytrash/TikTok-Livestream-Chat-Connector#20]
When I am trying to use this library in node, I get the error it cannot read 'security' of undefined as error. 

The channel is live and using the sample code.

**Comment by zerodytrash** [comment]
The entire library has no attribute named `security`. Possibly an error in one of the dependencies.
Can you provide more information like a stacktrace? 
Don't forget to handle the [error event](https://github.com/zerodytrash/TikTok-Livestream-Chat-Connector#error), which can provide additional information. 
Also check if your Node.js version is up to date.

**Comment by mrsydster** [comment]
It seems to be in the cookiejar dependency as far as I can see. My node version is 14.17.0 so that should be sufficient.


Stack trace: 
`Error: Failed to retrieve room_id from page source. Cannot read property 'secure' of undefined
    at WebcastPushConnection._retrieveRoomId2 (C:\Users\smits\Development\TwitchPlaysSD\node_modules\tiktok-livestream-chat-connector\dist\index.js:392:11)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async WebcastPushConnection.connect (C:\Users\smits\Development\TwitchPlaysSD\node_modules\tiktok-livestream-chat-connector\dist\index.js:242:7)`

**Comment by zerodytrash** [comment]
The axios-cookiejar-support dependency has been removed. Can you test if the problem is fixed? Don't forget to update the version.

**Comment by mrsydster** [comment]
@zerodytrash it's fixed! Thanks for the quick response and fix :)
