### ISSUE TITLE
check streamer is live

### ISSUE THREAD

**Issue by okuzlu** [zerodytrash/TikTok-Livestream-Chat-Connector#5]
tiktokChatConnection.connect() shows isConnected: true although the streamer is not streaming anymore. If I go via the url https://www.tiktok.com/@user/live there is a black screen and a text with "LIVE has ended 2.5K viewers".

How to check if the streamer goes live?

**Comment by okuzlu** [comment]
thank you. will use that workaround :)

**Comment by zerodytrash** [comment]
In the latest version, the `connect()` function raises an error if the room is in "LIVE has ended" state.
Furthermore, you can use the `getRoomInfo()` function to get the room info and check the status (as described above).
