### ISSUE TITLE
I can not see likes and followers

### ISSUE THREAD

**Issue by OlegShklyarov** [zerodytrash/TikTok-Livestream-Chat-Connector#6]
Hello! In Server.js I have added

```
        thisConnection.on('like', msg => socket.emit('like', msg));
        thisConnection.on('social', msg => socket.emit('social', msg));
```

In public app I have this:

```
socket.on('like', function(msg){
console.log("like");
console.log(msg.totalLikeCount);
});

socket.on('social', function(){
console.log("follow");
});
```

And there are no alerts coming. Gifts and chat are working fine. What am I doing wrong?

**Comment by zerodytrash** [comment]
hi,

the `like` and `social` event were introduced 2 days ago. I would assume that you need to update the package.

Simply run `npm i tiktok-livestream-chat-connector` to install the latest version.

**Comment by OlegShklyarov** [comment]
It helped, thank you! Could you please suggest, why can gifts come doubled? 

socket.on('gift', function(msg){

console.log("gift");
if (msg.giftId == "<?=$GIFT1;?>") {hp -= <?=$GIFT1A?>;gift1b.load();gift1b.play();console.log(msg.giftId)} 
if (msg.giftId == "<?=$GIFT2;?>") {hp -= <?=$GIFT2A?>;gift2b.load();gift2b.play();} 
if (msg.giftId == "<?=$GIFT3;?>") {hp -= <?=$GIFT3A?>;gift3b.load();gift3b.play();} 
if (msg.giftId == "<?=$GIFT4;?>") {hp += <?=$GIFT4A?>;gift4b.load();gift4b.play();console.log(msg.giftId)} 
if (msg.giftId == "<?=$GIFT5;?>") {hp += <?=$GIFT5A?>;gift5b.load();gift5b.play();} 
if (msg.giftId == "<?=$GIFT6;?>") {hp += <?=$GIFT6A?>;gift6b.load();gift6b.play();} 

});

They come one after another. 2 times one gift.

**Comment by zerodytrash** [comment]
Users have the capability to send gifts in a streak. This increases the `gift`.`repeat_count` value until the user terminates the streak. During this time new gift events are triggered again and again with an increased `repeat_count` value.
From what I have seen, the `repeat_count` value is not always correct. But this seems to be a tiktok issue...

![image](https://user-images.githubusercontent.com/59258980/153957952-3e94608e-ee54-47a0-bda1-ed812a94e30e.png)

Take a look at the latest reader demo, which now also displays gifts: https://github.com/zerodytrash/TikTok-Chat-Reader

**Comment by OlegShklyarov** [comment]
Hmmm... On our test streams even the first single gift came twice. There was no gift streaks before that user...

**Comment by zerodytrash** [comment]
does the problem also occur on https://tiktok-chat.herokuapp.com/ ?

**Comment by zerodytrash** [comment]
Looks correct to me.
![image](https://user-images.githubusercontent.com/59258980/153962523-9269bea8-489d-45c7-8075-0f361fd2dbea.png)

**Comment by OlegShklyarov** [comment]
It is working fine on Heroku. So it seems that my code is wrong?

**Comment by zerodytrash** [comment]
okay, i took a closer look and found out that tiktok transmits the gift with the final repeat count at the end of a streak. This happens even if the gift was sent only once by the viewer. But that doesn't always happen. Strange. To find out if the gift is a final streak summary, you can use the `repeat_end` property. It is set to `0` for a running streak and `1` for a finished streak. So if only one gift was sent, sometimes you will get two gift events. One with `repeat_end`:`0` and another with `repeat_end`:`1`.

in logic like this:
````javascript
if(data.gift.repeat_end === 1) {
   // streak end, process gift
} else {
   // is still in streak phase. ignore or show/count temporarily.
}
````
