### ISSUE TITLE
Is it possible to know, how many likes were sent on each tap event?

### ISSUE THREAD

**Issue by OlegShklyarov** [zerodytrash/TikTok-Livestream-Chat-Connector#7]
Hello! We can see the total amount of likes, but it is possible to see the count of each event? 
`A user XXX sent 34 likes. `

**Comment by zerodytrash** [comment]
hi, yes this is possible. But I have to add this to the protobuf schema. I will do it tomorrow.

**Comment by OlegShklyarov** [comment]
Good, good.jpg

**Comment by OlegShklyarov** [comment]
Hello! Could you please add a room_id string to like events? I need it to register stream performance.

**Comment by zerodytrash** [comment]
Hi, you can get the `room_id` from the connection.

````javascript
tiktokChatConnection.on('like', data => {`
    data.roomId = tiktokChatConnection.getState().roomId;
    console.log(`${data.uniqueId} sent ${data.likeCount} likes, total likes: ${data.totalLikeCount}; roomId: ${data.roomId}`);
})

````

**Comment by OlegShklyarov** [comment]
Thanks, you`re awesome.

**Comment by OlegShklyarov** [comment]
Could you please check? I do not see gift IDs 5587, 5880 on stream. Console returns nothing. 
![Untitled-1](https://user-images.githubusercontent.com/34983317/154864482-2c2ee420-a508-4d28-8ac9-7abe286991d1.jpg)

**Comment by zerodytrash** [comment]
Only gifts with `gift_type`:`1` are streakable. Other gift types can be processed immediately.

````javascript
  if (data.gift.gift_type === 1 && data.gift.repeat_end === 0) {
      // Streak in progress => show only temporary
      console.log(`${data.uniqueId} is sending gift ${data.giftId} x${data.gift.repeat_count}`);
  } else {
      // Streak ended or non-streakable gift => process the gift with final repeat_count
      console.log(`${data.uniqueId} has sent gift ${data.giftId} x${data.gift.repeat_count}`);
  }
````

**Comment by OlegShklyarov** [comment]
![Uploading robert-redford-yes.gif…]()
