### ISSUE TITLE
Accuracy with gifts

### ISSUE THREAD

**Issue by TopDogger1** [zerodytrash/TikTok-Livestream-Chat-Connector#8]
When running lives through your website ( https://tiktok-chat.herokuapp.com/ ) I seem to be getting a MUCH more accurate version of the data that I need, is there something that your doing that could help me more accurately receive gift data?

**Comment by zerodytrash** [comment]
Users have the capability to send gifts in a streak. This increases the `gift`.`repeat_count` value until the user terminates the streak. During this time new gift events are triggered again and again with an increased `repeat_count` value. It should be noted that sometimes after the end of the streak, another gift event is triggered, which signals the end of the streak via `repeat_end`:`1`. This applies only to gifts with `gift_type`:`1`. 

In the Chat Reader demo it is done like this:
````javascript
if (data.gift.gift_type === 1 && data.gift.repeat_end === 0) {
    // Streak in progress => show red 'Repeat' count
} else {
    // Streak ended => show black 'Repeat' count and count to 'earned diamonds'
}
````

**Comment by TopDogger1** [comment]
Ah that is perfect, thank you :)
