### ISSUE TITLE
[FEATURE REQUEST] TikTok Live Battles

### ISSUE THREAD

**Issue by viksra** [zerodytrash/TikTok-Livestream-Chat-Connector#9]
Requesting that you add functionality to capture, display and log TikTok Live battle scores (along with opponent name).

EDIT: Also requesting a checkbox/tickbox to enable/disable timestamps next to all events (gifts, likes, shares, follows, chat messages, etc.)

EDIT 2: Also requesting that the MODERATOR label and NEW GIFTER label is added next to usernames as appropriate

**Comment by zerodytrash** [comment]
> Requesting that you add functionality to capture, display and log TikTok Live battle scores (along with opponent name).

The library now contains events to monitor a battle.
Reference:
- https://github.com/zerodytrash/TikTok-Livestream-Chat-Connector#linkmicbattle
- https://github.com/zerodytrash/TikTok-Livestream-Chat-Connector#linkmicarmies

> EDIT: Also requesting a checkbox/tickbox to enable/disable timestamps next to all events (gifts, likes, shares, follows, chat messages, etc.)

We are here on the repository of the Node.JS library. I think you mean the chat reader, which is available here: https://github.com/zerodytrash/TikTok-Chat-Reader

> EDIT 2: Also requesting that the MODERATOR label and NEW GIFTER label is added next to usernames as appropriate

The library now indicates via the `userBadges` attribute whether the user is a moderator. 
Reference: 
- https://github.com/zerodytrash/TikTok-Livestream-Chat-Connector#chat

If you want to suggest adjustments to the chat-reader frontend, please create an issue in the correct repository as mentioned above.
